.github/workflows/merge.yml
---
- [Frontend](https://onroutebc-homepage-8-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-8-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: changed default input to empty string and made optional.

.github/workflows/merge.yml
---
- [Frontend](https://onroutebc-homepage-10-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-10-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: changed when test tagging gets run

frontend/Dockerfile, frontend/static_home_page/index.html
=> Change bceidboth to bceidbusiness, dashboard sub in dockerfile

frontend/static_home_page/notification.js
=> Test branch

frontend/static_home_page/css/styles.css, frontend/static_home_page/index.html
Added user guides with YouTube videos link
---
- [Frontend](https://onroutebc-homepage-15-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-15-frontend.apps.silver.devops.gov.bc.ca/api)
After …
=> feat: Added User Guides box

.github/workflows/analysis.yml
---
- [Frontend](https://onroutebc-homepage-17-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-17-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: remove npm tests from analysis (frontend)

.github/workflows/notifications.yml
---
- [Frontend](https://onroutebc-homepage-21-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-21-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: removed another bad reference to ms_teams_webhook_uri

frontend/static_home_page/notification.js
- [x ] New feature (non-breaking change which adds functionality)
---
- [Frontend](https://onroutebc-homepage-22-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-22-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/onroutebc-homepage/actions/workflows/ …
=> feat:  Outage notification for rel 38

frontend/static_home_page/notification.js
Update homepage notification message
Fixes [#ORV2-4048](https://moti-imb.atlassian.net/browse/ORV2-4048?atlOrigin=eyJpIjoiNDg2NDgwNmE3NTk5NDI4Mzg0MDM4OWQzZDFmZWQyMzEiLCJwIjoiaiJ9)
---
- [Frontend](https://onroutebc-homepage-25-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-25-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/onroutebc-homepage/actions/workflows/merge.yml)
=> feat: ORV2-4048 - Update homepage outage notification message

frontend/static_home_page/notification.js
=> notice off

frontend/static_home_page/notification.js
---
- [Frontend](https://onroutebc-homepage-27-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-27-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat:  Rel 39 try 2 outage

frontend/static_home_page/notification.js
---
- [Frontend](https://onroutebc-homepage-30-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-30-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: Flip notification to false

frontend/static_home_page/index.html.template
=> changed site text

.github/workflows/.deployer.yml, .github/workflows/.tests.yml, .github/workflows/demo.yml, .github/workflows/gold-dev.yml, .github/workflows/gold-prod.yml, .github/workflows/gold-test.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/pr-validate.yml, .github/workflows/scheduled.yml, .github/workflows/silver-dev.yml, .github/workflows/silver-prod.yml, .github/workflows/silver-test.yml, charts/app/README.md, charts/app/values.yaml, docker-compose.yml
---
- [Frontend](https://onroutebc-homepage-36-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-36-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> feat: transitioning homepage to gold cluster

.github/workflows/merge.yml
---
- [Frontend](https://onroutebc-homepage-38-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-38-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> fix: removed refrence to golddr.yml that does not exist

.github/workflows/gold-dev.yml, .github/workflows/gold-prod.yml, .github/workflows/gold-test.yml, .github/workflows/merge.yml, .github/workflows/silver-dev.yml, .github/workflows/silver-prod.yml, .github/workflows/silver-test.yml, charts/app/templates/frontend/templates/deployment.yaml
---
- [Frontend](https://onroutebc-homepage-40-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-40-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> fix: template substr mismatch

.github/workflows/gold-prod.yml, .github/workflows/merge.yml, .github/workflows/silver-prod.yml
---
- [Frontend](https://onroutebc-homepage-41-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-41-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> fix: workflow wrapper bug

.github/workflows/merge.yml, .github/workflows/pr-close.yml
---
- [Frontend](https://onroutebc-homepage-42-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-42-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> fix: cleanup gold

frontend/static_home_page/index.html.template
---
- [Frontend](https://onroutebc-homepage-43-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-43-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> fix(ORV2-5072): update Height clearance Tool link

.github/workflows/gold-demo.yml, .github/workflows/gold-dev.yml, .github/workflows/gold-prod.yml, .github/workflows/gold-test.yml, .github/workflows/gold-uat.yml, .github/workflows/merge.yml, .github/workflows/silver-demo.yml, .github/workflows/silver-dev.yml, .github/workflows/silver-test.yml, .github/workflows/silver-uat.yml, charts/app/templates/frontend/templates/deployment.yaml
---
- [Frontend](https://onroutebc-homepage-44-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-44-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> feat: uat and demo support

.github/workflows/gold-demo.yml, .github/workflows/gold-dev.yml, .github/workflows/gold-prod.yml, .github/workflows/gold-test.yml, .github/workflows/gold-uat.yml, .github/workflows/merge.yml, charts/app/templates/frontend/templates/deployment.yaml, charts/app/templates/frontend/templates/ingress.yaml, charts/app/values.yaml
---
- [Frontend](https://onroutebc-homepage-47-frontend.apps.gold.devops.gov.bc.ca)
- [Backend](https://onroutebc-homepage-47-frontend.apps.gold.devops.gov.bc.ca/api)
- [Merge …
=> feat: tls support
